tunnel: REPLACE_WITH_TUNNEL_ID
credentials-file: C:\\Users\\REPLACE_WITH_WINDOWS_USER\\.cloudflared\\REPLACE_WITH_TUNNEL_ID.json

ingress:
  - hostname: erp.domainkamu.com
    service: http://localhost:80
  - service: http_status:404
